export const myActions = {
  SORT_BY_STATE: "SORT_BY_STATE",
  SORT_BY_CITY: "SORT_BY_CITY",
  RIDE_DATA: "RIDE_DATA",
  OPEN_FILTER: "OPEN_FILTER",
  STATE_AND_CITY_SEARCH: "STATE_AND_CITY_SEARCH",
};
